In [1]:
# !pip install numpy --- required only when numpy is not installed

In [4]:
# import numpy
import numpy as np

In [6]:
# create an ND array from python list

mylist = [1, 2, 3, 4, 5]
type(mylist)

list

In [10]:
#np.array() : it will convert given object into an array

my_arr = np.array(mylist)
print(my_arr)

[1 2 3 4 5]


In [11]:
type(my_arr)

numpy.ndarray

In [13]:
print(mylist)
print(my_arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [ ]:
# mylist is python list that does not support much scientific calculation
# my_arr is nd array which supports math / scientific calculation

In [14]:
# just for demo purpose / no need to attempt this code

In [ ]:
import cv2

In [ ]:
pic=cv2.imread('sample_img.jpeg')

In [ ]:
pic

### Numpy vs Python

In [19]:
# speed # storage

In [35]:
# how much memory is consumed by single digit
num = 4

In [36]:
import sys

In [37]:
sys.getsizeof(num), 'bytes'

(28, 'bytes')

In [39]:
name = 'ShrikantRashu'

sys.getsizeof(name)

54

In [40]:
# for 1000 int we need 28000 bytes

In [43]:
my_arr

array([1, 2, 3, 4, 5])

In [45]:
# itemsize : return size of single elements in given array

In [47]:
my_arr.itemsize, 'bytes'

(8, 'bytes')

In [76]:
len(mylist)*28, 'bytes'

(140, 'bytes')

In [49]:
my_arr.nbytes, 'bytes'

(40, 'bytes')

In [ ]:
# we are saving 20000 bytes for 1000 number

In [50]:
import time

In [52]:
time.time()

1777277067.3491051

In [69]:
size = 1000000

l1 = range(size) # 0, 1, 2, 3
l2 = range(size) # 0, 1, 2, 3

ar1 = np.arange(size)
ar2 = np.arange(size)

start = time.time()
result = [x+y for x, y in zip(l1, l2)]
stop = time.time()

print("Time taken:", (stop - start)*1000, 'ms')

Time taken: 191.99872016906738 ms


In [70]:
size = 1000000

l1 = range(size) # 0, 1, 2, 3
l2 = range(size) # 0, 1, 2, 3

ar1 = np.arange(size)
ar2 = np.arange(size)

start1 = time.time()
result = ar1 + ar2
stop1 = time.time()

print("Time taken:", (stop1 - start1)*1000, 'ms')

Time taken: 17.617464065551758 ms


## Numpy ✅

In [77]:
# creating 1D array

In [78]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [83]:
print(a[-3])

3


In [82]:
print(a[2])

3


In [ ]:
# create 2D array

In [101]:
mylist = [[1, 2, 3, 4], [4, 5, 6, 7]]
new_arr = np.array(mylist)
new_arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [95]:
# shape : return rows and columns

In [102]:
new_arr.shape

(2, 4)

In [96]:
# .ndim : return number of dim

In [97]:
new_arr.ndim

2

In [98]:
a.ndim

1

In [100]:
a.shape # return number of data points in it

(5,)

In [103]:
# creating 3 dim array

In [109]:
mylist1 = [
    [[1,2,3],[4,5,6]],
    [[7,8,9], [10,11,12]]
]

c = np.array(mylist1)
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [110]:
c.shape

(2, 2, 3)

In [111]:
mylist2 = [
    [[1,2,3],[4,5,6]],
    [[7,8,9], [10,11,12]],
    [[1,5,6], [8,4,6]]
]

d = np.array(mylist2)
d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  5,  6],
        [ 8,  4,  6]]])

In [112]:
d.shape

(3, 2, 3)

In [113]:
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [117]:
print(c[0][1][1])

5


In [120]:
print(c[0][0][-2])

2


In [147]:
c[1][0][0]

np.int64(7)

In [153]:
c[0][1][1:]

array([5, 6])

In [157]:
new_arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [164]:
new_arr[1][1:]

array([5, 6, 7])

In [165]:
new_arr[1, 1:]

array([5, 6, 7])

In [173]:
new_arr[:, 3]

array([4, 7])

In [174]:
# stats operations

In [178]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype = 'float')
arr1

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [180]:
print(arr1.max())
print(arr1.min())
print(arr1.mean())
print(arr1.sum())

12.0
1.0
6.5
78.0


In [191]:
new_arr = arr1-arr1
new_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [192]:
print(new_arr.max())
print(new_arr.min())
print(new_arr.mean())
print(new_arr.sum())

0.0
0.0
0.0
0.0


In [193]:
x = np.array([[1,2],[3,4]])
y = np.array([[2,3],[4,5]])

In [194]:
x

array([[1, 2],
       [3, 4]])

In [195]:
y

array([[2, 3],
       [4, 5]])

In [196]:
x+y

array([[3, 5],
       [7, 9]])

In [197]:
x*y

array([[ 2,  6],
       [12, 20]])

In [198]:
x/y

array([[0.5       , 0.66666667],
       [0.75      , 0.8       ]])

In [199]:
x-y

array([[-1, -1],
       [-1, -1]])

In [203]:
# example

dist = [180,170,135,191,250]
time = [6,7,10,13,11]

d_arr = np.array(dist)
t_arr = np.array(time)

s_arr = (d_arr / t_arr)

s_arr

array([30.        , 24.28571429, 13.5       , 14.69230769, 22.72727273])

In [205]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [209]:
arr1[1:3, :2]

array([[4, 5],
       [7, 8]])

In [289]:
arr1[5]

array([11, 12])

In [210]:
# filtering array

In [211]:
s_arr

array([30.        , 24.28571429, 13.5       , 14.69230769, 22.72727273])

In [213]:
s_arr>20

array([ True,  True, False, False,  True])

In [215]:
s_arr[s_arr<20]

array([13.5       , 14.69230769])

In [216]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10,11,12]) 
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [220]:
arr2.shape

(12,)

In [221]:
arr2.ndim

1

In [222]:
# how to convert 1D array to 2D array

#reshape

In [223]:
# 1*12
# 2*6
# 3*4
# 4*3
# 6*2
# 12*1

In [245]:
arr2.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [226]:
arr2.reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [227]:
arr2.reshape(4, 3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [233]:
arr1 = arr2.reshape(6, 2)
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [229]:
arr2.reshape(12, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [230]:
arr2.reshape(5, 2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [234]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [235]:
arr1.T

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [242]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [246]:
# 1d to 3d
arr2.reshape(3, 2, 2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [247]:
arr2.ndim

1

In [248]:
arr2.reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [249]:
arr2.ndim

1

In [250]:
arr1.ndim

2

In [251]:
arr1.T

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [252]:
# 2d , 3d to 1d

arr1.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [256]:
np.arange(0, 15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [257]:
# .ones

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [262]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [273]:
np.eye(3, 3, dtype= int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [277]:
np.full((3,3), '*')

array([['*', '*', '*'],
       ['*', '*', '*'],
       ['*', '*', '*']], dtype='<U1')

In [280]:
np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [290]:
print(np.sin(np.pi))

1.2246467991473532e-16


In [291]:
print(np.sin(np.pi/2))

1.0


In [292]:
print(np.cos(np.pi))

-1.0
